"""Registration model — one row per attendee."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


class Registration(Base):
    __tablename__ = "registrations"

    id: Mapped[int] = mapped_column(primary_key=True)
    full_name: Mapped[str] = mapped_column(String(255), nullable=False)
    # E.164 format enforced by the phone service before insert.
    phone_e164: Mapped[str] = mapped_column(String(20), unique=True, nullable=False, index=True)
    church: Mapped[str] = mapped_column(String(255), nullable=False)
    attended_before: Mapped[bool] = mapped_column(Boolean, nullable=False)

    # Ticket fields — codes generated by services/tickets.py
    # Stored without the hyphen (XXXXXXXX); displayed as XXXX-XXXX.
    ticket_code: Mapped[str] = mapped_column(String(8), unique=True, nullable=False, index=True)
    # URL-safe token ≥ 16 bytes entropy for the personal ticket page.
    ticket_token: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)

    # "online" | "walk_in"
    source: Mapped[str] = mapped_column(String(10), nullable=False, default="online")

    # Set to the time OTP was verified; null means unverified (walk-ins bypass OTP).
    phone_verified_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    registered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # Check-in — set by volunteer on the day.
    checked_in_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    checked_in_by: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )

    # String-based forward references — no circular imports.
    checked_in_by_user: Mapped[list] = relationship(
        "User",
        back_populates="checked_in_registrations",
        foreign_keys="Registration.checked_in_by",
    )
    sms_logs: Mapped[list] = relationship("SmsLog", back_populates="registration")
    testimonials: Mapped[list] = relationship("Testimonial", back_populates="registration")

    def __repr__(self) -> str:
        return f"<Registration id={self.id} phone={self.phone_e164!r} code={self.ticket_code!r}>"
