"""initial schema

Revision ID: 188787996c2b
Revises: 
Create Date: 2026-10-05 02:24:51.828093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188787996c2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('donor_name', sa.String(length=255), nullable=True),
    sa.Column('donor_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_reference'), 'donations', ['reference'], unique=True)
    op.create_table('otp_codes',
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('phone_e164')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_open', sa.Boolean(), nullable=False),
    sa.Column('registration_closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('otp_enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_settings_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('other_names', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(length=100), nullable=False),
    sa.Column('student_status', sa.Boolean(), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('invitation_by_someone', sa.Boolean(), nullable=False),
    sa.Column('invitation_by_who', sa.String(length=255), nullable=True),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('church', sa.String(length=255), nullable=False),
    sa.Column('attended_before', sa.Boolean(), nullable=False),
    sa.Column('ticket_code', sa.String(length=8), nullable=False),
    sa.Column('ticket_token', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_token')
    )
    op.create_index(op.f('ix_registrations_phone_e164'), 'registrations', ['phone_e164'], unique=True)
    op.create_index(op.f('ix_registrations_ticket_code'), 'registrations', ['ticket_code'], unique=True)
    op.create_table('sms_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('to_phone', sa.String(length=20), nullable=False),
    sa.Column('template', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_log_registration_id'), 'sms_log', ['registration_id'], unique=False)
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('privacy_mode', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('private_name', sa.String(length=100), nullable=True),
    sa.Column('alias_name', sa.String(length=50), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testimonials')
    op.drop_index(op.f('ix_sms_log_registration_id'), table_name='sms_log')
    op.drop_table('sms_log')
    op.drop_index(op.f('ix_registrations_ticket_code'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_phone_e164'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('partners')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_donations_reference'), table_name='donations')
    op.drop_table('donations')
    # ### end Alembic commands ###
