"""Add location and accommodation_preference fields

Revision ID: e9d4c665b3de
Revises: 188787996c2b
Create Date: 2026-10-07 17:54:28.691690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d4c665b3de'
down_revision: Union[str, None] = '188787996c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('location', sa.String(length=150), server_default='Not Specified', nullable=False))
    op.add_column('registrations', sa.Column('accommodation_preference', sa.String(length=50), server_default='Not Specified', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'accommodation_preference')
    op.drop_column('registrations', 'location')
    # ### end Alembic commands ###
